// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHKrjiKGOByxK-kfGGmkMa6bPEIiItWLA',
    appId: '1:1061922346680:web:4c4a61655f76fbbab2c64d',
    messagingSenderId: '1061922346680',
    projectId: 'reddit-9e2aa',
    authDomain: 'reddit-9e2aa.firebaseapp.com',
    storageBucket: 'reddit-9e2aa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvINxvRZrt3NVmmLdZc88Il6EPc3gJMu4',
    appId: '1:1061922346680:android:323a5dc3983d03b3b2c64d',
    messagingSenderId: '1061922346680',
    projectId: 'reddit-9e2aa',
    storageBucket: 'reddit-9e2aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoL_GxOlSU3Y1pKftQ0NOj4RjOT0PxYgY',
    appId: '1:1061922346680:ios:5dfddfadaa3efc0cb2c64d',
    messagingSenderId: '1061922346680',
    projectId: 'reddit-9e2aa',
    storageBucket: 'reddit-9e2aa.appspot.com',
    iosClientId: '1061922346680-2fg4utflj8gaebgc09adrejt0n5ktv5t.apps.googleusercontent.com',
    iosBundleId: 'com.example.reddit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoL_GxOlSU3Y1pKftQ0NOj4RjOT0PxYgY',
    appId: '1:1061922346680:ios:5dfddfadaa3efc0cb2c64d',
    messagingSenderId: '1061922346680',
    projectId: 'reddit-9e2aa',
    storageBucket: 'reddit-9e2aa.appspot.com',
    iosClientId: '1061922346680-2fg4utflj8gaebgc09adrejt0n5ktv5t.apps.googleusercontent.com',
    iosBundleId: 'com.example.reddit',
  );
}
